import{i as l,S as u}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function f(s){const o="https://pixabay.com",t="/api/",n=new URLSearchParams({key:"44189121-1bd84ab9c2376b17257837ab7",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${o}${t}?${n}`;return fetch(e).then(r=>{if(!r.ok)throw new Error("Failed to fetch images");return r.json()})}function p(s){const o=document.querySelector(".img-container");o.innerHTML=s.map(t=>`<a href="${t.largeImageURL}"  class="gallery-item" >
<img src="${t.webformatURL}" alt="${t.tags}" />
<div class="info">¨
  <p class="info-title">Likes: <span class="info-value">${t.likes}</span> </p>
  <p class="info-title">Views: <span class="info-value">${t.views}</span></p>
  <p class="info-title">Comments: <span class="info-value">${t.comments}</span></p>
  <p class="info-title">Downloads: <span class="info-value">${t.downloads}</span></p>
</div>
</a>`).join("")}function d(){document.querySelector(".loader").style.display="block"}function c(){document.querySelector(".loader").style.display="none"}function a(s){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}const m=document.querySelector(".form");m.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements.query.value.trim();if(!o){a();return}d(),f(o).then(t=>{if(c(),t.hits.lenght===0){a();return}p(t.hits),new u(".img-container a").refresh()}).catch(t=>{c(),a()})});
//# sourceMappingURL=commonHelpers.js.map
