import{i as l,S as u}from"./assets/vendor-8c59ed88.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function f(o){const n="https://pixabay.com/api/",r=new URLSearchParams({key:"44189121-1bd84ab9c2376b17257837ab7",q:"query",image_type:"photo",orientation:"horizontal",safesearch:"true"}),s=`${n}?${r}`;return fetch(s).then(e=>{if(!e.ok)throw new Error("Failed to fetch images");return e.json()})}function d(o){const n=document.querySelector(".img-container");n.innerHTML=o.map(r=>`<a href="${r.largeImageUrl}"  class="gallery-item" >
<img src="${r.webformatUrl}" alt="${r.tags}" />
<div class="info">¨
  <p>Likes: ${r.likes}</p>
  <p>Views: ${r.views}</p>
  <p>Comments: ${r.comments}</p>
  <p>Downloads: ${r.downloads}</p>
</div>
</a>`).join("")}function c(){document.querySelector(".loader").style.display="none"}function a(o){l.error({title:"Error",message:o})}const m=document.querySelector(".form");m.addEventListener("submit",o=>{if(o.preventDefault(),!o.target.elements.query.value.trim()){a("Please enter a search query!");return}f().then(r=>{if(c(),r.hits.lenght===0){a(" Sorry, there  are no images matching your search query. Please try again!");return}clearGallery(),d(r.hits),new u(".img-container a").refresh()}).catch(r=>{c(),a("Failed to fetch images. Please try again later!")})});
//# sourceMappingURL=commonHelpers.js.map
